sudo: required
services:
  - docker

before_install:
  - docker build -t edneedham/react-test -f ./client/Dockerfile.dev ./client

script:
  - docker run -e CI=true edneedham/react-test npm test

after_success:
  - docker build -t edneedham/multi-client ./client
  - docker build -t edneedham/multi-nginx ./nginx
  - docker build -t edneedham/multi-server ./server
  - docker build -t edneedham/multi-worker ./worker
  # Login to the docker CLI
  - echo "$DOCKER_PASSWORD" | docker login -u "$DOCKER_ID" --password-stdin
  # Take those images and push them to docker hub
  - docker push edneedham/multi-client
  - docker push edneedham/multi-nginx
  - docker push edneedham/multi-server
  - docker push edneedham/multi-worker

deploy:
  provider: elasticbeanstalk
  region: eu-west-2
  app: multi-docker
  env: MultiDocker-env
  bucket_name: elasticbeanstalk-eu-west-2-145443410278
  bucket_path: docker-multi
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY